### ISSUE TITLE
作者可不可以添加一个下载文件夹的功能呢

### ISSUE THREAD

**Issue by still-night** [Mrs4s/BaiduPanDownload#10]

**Comment by Izumiko** [comment]
直接复制文件夹下载地址的话，用递归几行代码就能实现，但复制出的下载地址没有保留目录结构。

我之前自己改的代码是复制出aria2中可用的下载地址，可以在复制的下载地址后边添加保存目录的参数，就能保存目录结构了。

作者可以考虑加上个“复制下载地址到aria2”的功能，或者直接调用aria2下载？

**Comment by Mrs4s** [comment]
目前在解决限速问题 下载文件夹的功能一直都是有的 右键 下载 添加到下载列表
会保留文件结构

**Comment by ZhiDongLuo** [comment]
本还想自己改下功能呢，就限速了~~~~

**Comment by Izumiko** [comment]
@Mrs4s 好吧，没注意到软件中可以。。。之前用的时候看到你的提示建议复制下载地址到其他软件下载，就没再用过内置的下载功能，一直是用树莓派+移动硬盘下。

**Comment by Mrs4s** [comment]
@Izumiko 因为是内置的下载 所以解决目录结构之类的还是很简单的

**Comment by Mrs4s** [comment]
@ZhiDongLuo  目前已更新高速下载
