### ISSUE TITLE
用IDM调整线程数可以临时解决限速问题

### ISSUE THREAD

**Issue by Zeyugao** [Mrs4s/BaiduPanDownload#11]
![image](https://cloud.githubusercontent.com/assets/6374697/20034451/915697f0-a3f9-11e6-9ffd-95ec16a91f75.png)
原先8线程时也是大概10Mbps，800~900KBps的节奏，调到32线程就可以满载了，感觉太暴力了

**Comment by Mrs4s** [comment]
我测试了下。。百M满速需要开92个线程

**Comment by zl810881283** [comment]
你是什么版本的IDM？我用的话总是400 Bad Request
