### ISSUE TITLE
实现不限速的原理是啥，可以说一下不？

### ISSUE THREAD

**Issue by zhuxiaole** [Mrs4s/BaiduPanDownload#14]
大神，原理可以说一下不？

**Comment by xuxiaoyuspallow** [comment]
加一

**Comment by autopanda** [comment]
https://github.com/Mrs4s/BaiduPanDownload/blob/master/BaiduPanDownload/Forms/Login.cs#L35
申请的BOS的api吧

**Comment by Mrs4s** [comment]
@autopanda 正解
