### ISSUE TITLE
idm上连接好像用不了

### ISSUE THREAD

**Issue by Gordon-shin** [Mrs4s/BaiduPanDownload#16]
显示http 400 bad request

**Comment by BlueSplash** [comment]
https://github.com/Mrs4s/BaiduPanDownload/pull/15

**Comment by Mrs4s** [comment]
感谢提出 最新版本已修复这个bug
@BlueSplash 我测试你的方案似乎不可行,目前采用的是@Izumiko的方案 不过还是感谢您！
