### ISSUE TITLE
【登录界面加载不了】

### ISSUE THREAD

**Issue by SJTUboy** [Mrs4s/BaiduPanDownload#21]
最新1.6版，无法加载登录界面，操作环境：WIN10  64bits
另附截图
![capture 1](https://cloud.githubusercontent.com/assets/13373715/20205375/3bf9b4ae-a813-11e6-9ecc-07fb00cd3751.png)

**Comment by Mahayu** [comment]
首先可以试试看左下角的那个按钮……
不行的话你可以试着清除一下IE缓存
