### ISSUE TITLE
下载产生大量碎片。

### ISSUE THREAD

**Issue by kokutoukiritsugu** [Mrs4s/BaiduPanDownload#24]
![snipaste20161112_170538](https://cloud.githubusercontent.com/assets/5471433/20236764/5ee920f2-a8fa-11e6-8ca4-372e61874078.png)

估计是合并文件时产生的。

能做成只产生单个文件，并只在单个文件里写入，并且保持现在的多线程下载吗？

**Comment by Mrs4s** [comment]
可以 我正在写 这个下载方案是基于网上抄的代码改的
准备自己重写了 另外断点续传下个版本也会加入
