### ISSUE TITLE
发生错误时的MessageBox太多了吧

### ISSUE THREAD

**Issue by Zeyugao** [Mrs4s/BaiduPanDownload#3]
![8](https://cloud.githubusercontent.com/assets/6374697/19826058/17db0630-9db5-11e6-872b-6c5791a9b6ec.png)
你这是让我情何以堪

**Comment by Mrs4s** [comment]
感谢提出 马上解决这个问题 另外你这个下载失败的原因是文件名有特殊字符。。

**Comment by Mrs4s** [comment]
修复了哦^_^
