### ISSUE TITLE
运行时提示401ERROR

### ISSUE THREAD

**Issue by cookgreen** [Mrs4s/BaiduPanDownload#30]
成功登录，获取列表时提示异常，断点调试发现401认证ERROR

**Comment by cookgreen** [comment]
![error123](https://cloud.githubusercontent.com/assets/21171007/20303435/54460322-ab66-11e6-8cbe-d01a7437695a.JPG)

**Comment by Mrs4s** [comment]
请问是不是登录的时候吧[授权应用访问个人文件夹]的勾去掉了
目前我只有这样才成功还原这个异常

**Comment by cookgreen** [comment]
好吧
