### ISSUE TITLE
下载时导致磁盘占用飙升，导致文件传输极其缓慢

### ISSUE THREAD

**Issue by nilaoda** [Mrs4s/BaiduPanDownload#36]
复制文件直接降到1m/s，影响太大了，磁盘占用率超级高，尤其是合并是，简直欲仙欲死……

**Comment by cor961** [comment]
你硬盘太差了吧？还是一次下载的文件太多？

**Comment by cmsax** [comment]
建议换个固态

获取 Outlook for Android<https://aka.ms/ghei36>



On Sat, Nov 19, 2016 at 12:48 PM +0800, "nilaoda" <notifications@github.com<mailto:notifications@github.com>> wrote:


复制文件直接降到1m/s，影响太大了，磁盘占用率超级高，尤其是合并是，简直欲仙欲死……

―

**Comment by nilaoda** [comment]
我有固态，但是在机械里面下东西。平时传文件有80+m/s，一用这个下载东西瞬间降到个位数……其他迅雷、115都不影响，就是这个老司机的太费硬盘了，我都怕硬盘报废……

**Comment by Mrs4s** [comment]
下载时分块很多 机械肯定撑不住
我下载都用固态的
这没办法解决 机械性能太差了

**Comment by Mrs4s** [comment]
对了迅雷一个文件一般只有五个分块 我这个软件多的时候一个文件一百多个分块
机械硬盘随机性能太差 不卡才有鬼。。

**Comment by nilaoda** [comment]
为什么IDM那种也是分片下载，就没有这么严重呢？我还是先下到固态，然后再移动吧……
![qq 20161119135507](https://cloud.githubusercontent.com/assets/20772925/20453445/42aaac10-ae60-11e6-90bb-0207d80f17f5.png)

**Comment by Mrs4s** [comment]
IDM也就16个分片。。百度云限速了 我开了100+分片。。这就是为啥这么吃硬盘

**Comment by nilaoda** [comment]
知道了。我先下到固态吧。那个下次更新能不能增加批量操作啊，一个一个停止太累了

**Comment by Mrs4s** [comment]
下次更新主要是断点续传。。我现在在马字 批量的话下下次吧 开的线程太多 批量停止容易崩溃

**Comment by nilaoda** [comment]
好的 对了希望增加下载完成后的提示~

**Comment by NAVrasZ** [comment]
@Mrs4s 所以...用IDM就没有高速下载了？

**Comment by Mrs4s** [comment]
@NAVrasZ 对的
