### ISSUE TITLE
1.7版bug汇报

### ISSUE THREAD

**Issue by loveproe** [Mrs4s/BaiduPanDownload#37]
1.现在不能下载文件夹啦，一下载提示文件太小。
2.修改了下载方式没有下载自定义了。但是解决了合并文件太慢的问题。
3.但是问题是下载到99.999.。%s甚至100%后面的状态还是停止中。。。
4.进入下载目录发现下载文件的配置文件dcj没有删除。
5.下载文件管理不能删除任务？

**Comment by Mrs4s** [comment]
第一个问题:疏忽了 改了下载方式做了个文件大小判断 但是忘记了文件夹大小本身是0
第二个问题:下载自定义是啥。。
第三个问题:没看懂
第四个问题:dcj主要是储存的下载信息 用于断点续传的 忘记设置自动删除了
第五个问题:正在解决

**Comment by loveproe** [comment]
2.就是下载可以自己定义下载线程数量，下载没有了。
3.看图，一直显示停止中也不知道是不是下载完了，但是能播放。
![qq 20161119160101](https://cloud.githubusercontent.com/assets/13557821/20454135/f5a3c584-ae71-11e6-9f94-956252985260.png)

**Comment by Mrs4s** [comment]
下载线程现在就是根据网速自动设置了(说是自动 其实挺智障的。。)
第二个停止中是因为偷懒 吧下载完成和暂停设置成一个提示了 下载到99以上状态变为停止中就是下载完成了

**Comment by Mrs4s** [comment]
已更新
