### ISSUE TITLE
1.71bug反馈

### ISSUE THREAD

**Issue by nilaoda** [Mrs4s/BaiduPanDownload#38]
提示下载完成，百分百不到一百……dcj文件没有自动删除
![qq 20161119174153](https://cloud.githubusercontent.com/assets/20772925/20454569/8b37fd1a-ae7f-11e6-9631-7201947c8c4d.png)

**Comment by nilaoda** [comment]
且经常性的没速度

**Comment by Mrs4s** [comment]
下载到最后没速度暂时没办法。。暂停重试吧

**Comment by nilaoda** [comment]
好吧 先用1.6版本下载~

**Comment by Mrs4s** [comment]
1.7下载到中途没速度的话有可能是硬盘跟不上 建议上SSD下载

**Comment by nilaoda** [comment]
已经是下载到ssd了  1.6下载到ssd的话还是好用的  刚才1.71也是ssd半路就没速度，还得暂停重试。我下载的是文件夹，好麻烦的，还是用1.6吧先

**Comment by kokutoukiritsugu** [comment]
下载到最后没速度
暂停重试可以继续下完，
能做个比如30秒速度一直为零自动暂停重试吗

**Comment by Mrs4s** [comment]
@kokutoukiritsugu 可以加入 明天试试吧

**Comment by loveproe** [comment]
@Mrs4s 这里有个容易犯错的地方，就是我看到下载中没有速度，我就没有先暂停，而是直接点了继续，这个时候就会从头开始下载。。。建议状态不是暂停中的时候，继续这个变灰不能选比较合适。。。
