### ISSUE TITLE
1.71 中途0kb/s的发生率太高了

### ISSUE THREAD

**Issue by nilaoda** [Mrs4s/BaiduPanDownload#39]
而且也没有提示，不能自动暂停继续，简直要命了，添加任务半天结果就下了不到一半就都没速度了……

**Comment by Mrs4s** [comment]
下个版本加上日志 我这边确实复现不出来情况呢

**Comment by nilaoda** [comment]
我是联通网络  1.71版本经常行的0kb/s。。然而1.6又容易导致文件错误。。dev要加油啊

发自我的 Windows Phone
________________________________
发件人: Mrs4s<mailto:notifications@github.com>
发送时间: ‎2016/‎11/‎20 22:18
收件人: Mrs4s/BaiduPanDownload<mailto:BaiduPanDownload@noreply.github.com>
抄送: nilaoda<mailto:nilaoda@live.com>; Author<mailto:author@noreply.github.com>
主题: Re: [Mrs4s/BaiduPanDownload] 1.71 中途0kb/s的发生率太高了 (#39)


下个版本加上日志 我这边确实复现不出来情况呢

**Comment by shengdie** [comment]
是的，下了一个7个G的东西，之前速度不错，到了97%速度变成0了，暂停再继续也只是偶尔有几十kb的速度，又下了几个小时也只是到98%，然后基本就不动了，之前白下了，希望可以解决这问题，不然一开始速度再快也是徒劳。

**Comment by donly** [comment]
刚测试1.7.5版本，Win7 64位，带宽100M，速度能达12M/S，SSD 硬盘，结果到96%左右停住了
