### ISSUE TITLE
作者啊，我们不需要你这个的下载功能，只需要能提取地址就可以了啊，别的下载工具比你快多了，完全没必要用这个下载的

### ISSUE THREAD

**Issue by fuckourselves** [Mrs4s/BaiduPanDownload#43]
作者啊，我们不需要你这个的下载功能，只需要能提取地址就可以了啊，别的下载工具比你快多了，完全没必要用这个下载的

**Comment by itodouble** [comment]
你这样说出来就不好了 发自网易邮箱大师 在2016年11月23日 09:41 ，fuckourselves写道： 作者啊，我们不需要你这个的下载功能，只需要能提取地址就可以了啊，别的下载工具比你快多了，完全没必要用这个下载的 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by Mrs4s** [comment]
请问什么下载工具比较快呢 我可以尝试直接调用外部下载工具下载

**Comment by itodouble** [comment]
我用的是渣雷

**Comment by Mrs4s** [comment]
@itodouble 迅雷的话只有热门资源可以靠离线加下速 如果遇到没法加速的资源就比较慢

**Comment by itodouble** [comment]
不啊 我昨天下了一个6G的资源  速度挺快的  我还故意限速2M （可能是因为我在公司的原因） 你可以试试

**Comment by Mrs4s** [comment]
离线成功了吗 我记得迅雷如果没有离线下载速度也就1-2M/s  我这个工具可以跑到12M/s以上

**Comment by itodouble** [comment]
我没有进行离线  我就只是直接下载  速度太高了  影响办公

**Comment by Mrs4s** [comment]
@itodouble 好吧因为我是下载党 喜欢收集资源 所以下载是越快越好  我可以试试调用迅雷下载

**Comment by potkeys2** [comment]
@Mrs4s 确实如果提取到的链接不限速的话，迅雷会稳定好多

**Comment by Mrs4s** [comment]
@potkeys2  可惜百度吧链接限速了 少部分迅雷会员能离线 但是我测试很多资源都没办法 其实现在这个程序下载不稳定也是限速的锅 11月之前没限速的时候下载体验其实很稳定的

**Comment by dq19871123** [comment]
这样的话直接给个选项，使用自带下载功能还是调用第三方工具，调用的话用户直接命令行，该选项保存到配置文件中。
ps：有谁知道Orbit的命令行如何传cookies？

**Comment by zcy85611** [comment]
很有用的功能，不是每个人都开了迅雷的会员。建议保留，并改进功能。目前下载存在的问题：1.不能终止/删除现有下载。 2. 不能对同时下载的进程数进行控制。 3. 不能限制速度。 4. 有下载超过99%实际已经完成但进度不到100%的情况。 总体来说非常好的工具，感谢Mrs4s的辛勤劳动，希望越做越好，为了项目能够持久，可以考虑在下载器里加入一些内嵌的广告，我保证会去多点几下。

**Comment by lzyroot** [comment]
建议直接在现有版本的基础上增加复制下载地址的功能就好了

**Comment by donly** [comment]
不需要做太多功能，下载工具个人认为支持一键发送到aria2 rpc就够了

**Comment by Mrs4s** [comment]
@lzyroot 有复制下载地址的功能的

**Comment by Mrs4s** [comment]
@donly  只在路由器用过aria2 回头看看有没有啥接口 尽量做

**Comment by cmsax** [comment]
对于绝大部分用户来说，集成式的服务是有必要的。


________________________________
发件人: fuckourselves <notifications@github.com>
发送时间: 2016年11月23日 1:41
收件人: Mrs4s/BaiduPanDownload
主题: [Mrs4s/BaiduPanDownload] 作者啊，我们不需要你这个的下载功能，只需要能提取地址就可以了啊，别的下载工具比你快多了，完全没必要用这个下载的 (#43)


作者啊，我们不需要你这个的下载功能，只需要能提取地址就可以了啊，别的下载工具比你快多了，完全没必要用这个下载的

―

**Comment by donly** [comment]
@Mrs4s [acgotaku](https://github.com/acgotaku/) 大大做过一个类似的，以前用过就是速度不快，[传送门](https://github.com/acgotaku/BaiduExporter)

**Comment by fuckourselves** [comment]
@Mrs4s 作者大人，idm啊，我一般都是在你那里提取地址，丢到idm下的，至少目前没有比它更快的了。
我不常上github，抱歉现在才回哈，我觉得这个工具就专注于提取不限速的地址 就好了，百度云直接点下载的地址是限速的，我只想要一个不限速的地址，专注做到这一点就好啦，作者大人，完全没必要自己去弄一个下载的啊！
btw，你的头像好可爱啊

**Comment by soulomoon** [comment]
@fuckourselves I'll be typing in English since I have no access to a Chinese IME.  
when I am using IDM, the max speed is approximately 3 m/s to 4 m/s in an 100m
wifi network connection even if I try my best to optimize my setting in IDM. 
Obviously not fast enough to run up my network.
While using this tool, the speed would be up to 10 m/s to 12 m/s.
and here thanx the auther

**Comment by wanglongqi** [comment]
@Mrs4s aria2 集成比较容易。两种途径一种是命令行集成，就只需要前面加一段固定的命令行参数就行；另一种是rpc的，官网有示例代码，基本也是现成。

**Comment by NAVrasZ** [comment]
idm一点都不快...明显能看出被限速了
之前为了下个大文件入正idm，然后才发现复制下载链接到idm里并不能破限速（躺

**Comment by wanglongqi** [comment]
@NAVrasZ 说实在的我不能理解为什么IDM会快，限速是服务器端的事情，一个链接要么没有限速要么限速了，和你用IDM还是aria2下载会有区别吗？

**Comment by NAVrasZ** [comment]
@wanglongqi 因为之前有用段时候说idm下度盘链接不限速，然后私以为限速开32个线程就好了（然而实际只有4个
然而入正还是因为看到之前那个下载碎片太多的问题，plus正(心)好(甘)想(情)要(愿)一个比较强力的下载工具

**Comment by Mrs4s** [comment]
@NAVrasZ  现在这个程序下载应该没啥大bug了吧 已知bug我都正在修了 不是特别影响下载 下载碎片的问题也已经解决了

**Comment by NAVrasZ** [comment]
@Mrs4s 谢大大，最近下载都没有问题的说~

**Comment by wanglongqi** [comment]
@Mrs4s 这个程序在Mac上应该是没有希望编译吧？

**Comment by Mrs4s** [comment]
@wanglongqi 没办法的。。我也想做跨平台 但是能力有限 想做个安卓版 会Java但是没相关教程还是放弃了

**Comment by wanglongqi** [comment]
@Mrs4s 看来跨平台最靠谱还是直接做插件呀，JS好像有大量的可用代码，不知道有经验不？

**Comment by Mrs4s** [comment]
@wanglongqi 浏览器插件应该做不出来 除非能自己写下载的核心代码

**Comment by wanglongqi** [comment]
@Mrs4s https://github.com/acgotaku/BaiduExporter 的思路感觉挺不错的，插件只负责提取链接，下载交给aria2，aria2毕竟是专业的下载工具，效果还是很好的。

**Comment by Mrs4s** [comment]
@wanglongqi 准备做个浏览器插件 提取下载链接发到下载器下载 就和云管家差不多的那种 不过不会js。。

**Comment by fuckourselves** [comment]
@Mrs4s 作者，我昨天试了你的自带下载，也是被限速啊，跟用idm没分别，idm还快一点啊，我不知道上面说自带下载好用的是什么环境，反正我觉得还是提取地址用idm下比自带快一些，虽然也被限速，这一点似乎没法解决。。。

**Comment by cor961** [comment]
反正我win10（1607、1155）、联通100M，用这个工具直接下一直都能满速，我没用过idm，不过用idm下也不可能更快了吧？唯一的一点不便是无法记住下载位置。
你们下不到满速的到底是多大带宽啊？

**Comment by fuckourselves** [comment]
@cor961 我电信的，反正自带就是被限速，还不如idm，人idm是专业的下载软件，总不会比这个差，实际也是这样

**Comment by Mrs4s** [comment]
@fuckourselves 没速度有两种可能 1.带宽设置不正确 2.硬盘速度跟不上
大多数人的环境下下载都是比idm快的 当然不排除特殊环境

**Comment by ftsm** [comment]
电信，idm只有2m，用自带的可以到10m，可惜并不支持200mbps带宽啊。

**Comment by caoli5288** [comment]
自带的下载比idm快得多
