### ISSUE TITLE
百度网盘api

### ISSUE THREAD

**Issue by xiaofan2406** [Mrs4s/BaiduPanDownload#48]
作者 你好

请问 你这软件在百度开发者中心是怎么设置的， 很多教程都说要开发pcs api 权限，但是那些链接完全找不到？ 可以加微信私聊吗

这里的文档： http://developer.baidu.com/wiki/index.php?title=docs/pcs/guide/api_approve
但是： 开放API > API管理 > API列表 完全找不到

**Comment by Mrs4s** [comment]
百度现在不让申请了。。
