### ISSUE TITLE
1.76总体上已经很不错了，希望增加以下功能

### ISSUE THREAD

**Issue by nilaoda** [Mrs4s/BaiduPanDownload#51]
## 我期望的功能
* 标题栏显示下载速度
* Win7以上支持任务栏进度条
* Json文件中有**TaskNum**设置，希望软件中也能加入
* 望在1.8版本能真正彻底解决速度为0K的问题
* 悬浮窗
* 再遇到持续10s以上的0K/s时能弹出提示框，或自动暂停继续
* 网盘文件希望能够以列表形式展示而不是图标
* 下载完成后的提示音

暂时就能想到这么多了，加油！

**Comment by nilaoda** [comment]
@Mrs4s

**Comment by Mrs4s** [comment]
基本没问题 悬浮窗的话要解决全屏应用自动隐藏的问题 如果有dalao有方案的话欢迎留言

**Comment by kokutoukiritsugu** [comment]
网盘列表显示+10086
能有文件大小就更好了(*^_^*)
