### ISSUE TITLE
好像没什么速度了

### ISSUE THREAD

**Issue by hexianfu** [Mrs4s/BaiduPanDownload#58]
昨晚才发现这个工具，昨天晚上下载还能满带宽下载，刚刚下载只有500K左右了

**Comment by freesd** [comment]
今天下载发现这个也限速了，最高700多K左右，上不去了

**Comment by Mrs4s** [comment]
经测试还能满速下载,请提供下运营商和设置？

**Comment by hexianfu** [comment]
@Mrs4s  电信啊，要什么设置啊？

**Comment by hexianfu** [comment]
没改过什么设置啊！那天晚上能满速，没动过设置，第二天打开电脑想继续下载就没速度了
