### ISSUE TITLE
3个小问题 反馈与建议

### ISSUE THREAD

**Issue by catshitz** [Mrs4s/BaiduPanDownload#69]
版本1.7.7 不知以下几点是否已提过 若有重复 还请谅解
1.实时下载速度不稳定（上下浮动略大 但平均值符合物理带宽理论下载值 比百毒强多了 点赞）
2.下载目录默认BaiduYunDownload不能自定义 点击无效（当然亦可直链IDM 并无大碍）
3.望加入限速功能 以减少对其他程序网速影响
以上 非常感谢

**Comment by coderstory** [comment]
还有一点  下载列表 哪怕没有正在下载的任务 也会定是刷新

**Comment by Mrs4s** [comment]
回复:
@catshitzhou 1.这个只有尽量优化,百度限速了的 分享的直链放到IDM照样速度跳动大 2.写新的UI时疏忽了 下个版本修复 3.在下载功能足够稳定后再加入

@coderstory 已修复,下个版本更新

**Comment by NAVrasZ** [comment]
ps:能否让下载速度显示的位数少一点，觉着小数点后2位就差不多...
