### ISSUE TITLE
百度已经把你的特殊文件夹名称封掉了，赶紧该一个吧

### ISSUE THREAD

**Issue by anole1980** [Mrs4s/BaiduPanDownload#7]
已经无法在百度网盘根文件夹下创建 “我的应用数据” 这个文件夹了，看来百度是要恶心到死了！

**Comment by Mrs4s** [comment]
您好 我拿全新的账号测试了下 还能用的。。估计你遇到了啥奇怪的问题 方便的话可以加QQ1844812067我帮忙看看？
