### ISSUE TITLE
能不能有个同时复制多个文件的URL这样的功能呢?

### ISSUE THREAD

**Issue by linjunshi** [Mrs4s/BaiduPanDownload#8]
您好, 非常感谢您的制作的这个软件, 请问, 能不能在选中多个文件的时候点击右键复制链接时, 能自动生成多个url然后以换行符为分隔符呢? 像迅雷的话是可以支持多个url同时下载但是是要以换行符为分隔符的, 因为有很多人是要同时下载多个文件, 如果有这样的功能那就好了, 谢谢

**Comment by Mrs4s** [comment]
已经有人pull了这个功能 有能力的话可以自己下载编译 实在不行的话可以等我下个版本一块编译
