### ISSUE TITLE
打开软件就提示错误！

### ISSUE THREAD

**Issue by vmvz** [Mrs4s/BaiduPanDownload#86]
https://ooo.0o0.ooo/2016/12/05/584506e46ab4c.jpg
最新版的出现了这个情况。

**Comment by Mrs4s** [comment]
能否将完整的错误报告贴出

**Comment by vmvz** [comment]
有关调用实时(JIT)调试而不是此对话框的详细信息，
请参见此消息的结尾。

************** 异常文本 **************
System.Security.SecurityException: 不允许所请求的注册表访问权。
   在 Microsoft.Win32.RegistryKey.OpenSubKey(String name, Boolean writable)
   在 System.Windows.Forms.LinkUtilities.GetIELinkBehavior()
   在 System.Windows.Forms.LinkUtilities.EnsureLinkFonts(Font baseFont, LinkBehavior link, Font& linkFont, Font& hoverLinkFont)
   在 System.Windows.Forms.LinkLabel.OnPaint(PaintEventArgs e)
   在 System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   在 System.Windows.Forms.Control.WmPaint(Message& m)
   在 System.Windows.Forms.Control.WndProc(Message& m)
   在 System.Windows.Forms.Label.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
失败的程序集的区域是:
MyComputer


************** 已加载的程序集 **************
mscorlib
    程序集版本: 4.0.0.0
    Win32 版本: 4.0.30319.18063 built by: FX45RTMGDR
    基本代码: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
BaiduPanDownload
    程序集版本: 1.7.8.0
    Win32 版本: 1.7.8.0
    基本代码: file:///E:/d/V1.7.8/BaiduPanDownload.exe
----------------------------------------
System.Windows.Forms
    程序集版本: 4.0.0.0
    Win32 版本: 4.0.30319.34251 built by: FX452RTMGDR
    基本代码: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    程序集版本: 4.0.0.0
    Win32 版本: 4.0.30319.34270 built by: FX452RTMGDR
    基本代码: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System
    程序集版本: 4.0.0.0
    Win32 版本: 4.0.30319.34238 built by: FX452RTMGDR
    基本代码: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
Newtonsoft.Json
    程序集版本: 9.0.0.0
    Win32 版本: 1.7.8.0
    基本代码: file:///E:/d/V1.7.8/BaiduPanDownload.exe
----------------------------------------
log4net
    程序集版本: 1.2.15.0
    Win32 版本: 1.7.8.0
    基本代码: file:///E:/d/V1.7.8/BaiduPanDownload.exe
----------------------------------------
System.Core
    程序集版本: 4.0.0.0
    Win32 版本: 4.0.30319.17929 built by: FX45RTMREL
    基本代码: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Numerics
    程序集版本: 4.0.0.0
    Win32 版本: 4.0.30319.17929 built by: FX45RTMREL
    基本代码: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    程序集版本: 4.0.0.0
    Win32 版本: 4.0.30319.34234 built by: FX452RTMGDR
    基本代码: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Xml.Linq
    程序集版本: 4.0.0.0
    Win32 版本: 4.0.30319.17929 built by: FX45RTMREL
    基本代码: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Xml
    程序集版本: 4.0.0.0
    Win32 版本: 4.0.30319.34234 built by: FX452RTMGDR
    基本代码: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Data
    程序集版本: 4.0.0.0
    Win32 版本: 4.0.30319.17929 built by: FX45RTMREL
    基本代码: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Configuration
    程序集版本: 4.0.0.0
    Win32 版本: 4.0.30319.18060 built by: FX45RTMGDR
    基本代码: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Web
    程序集版本: 4.0.0.0
    Win32 版本: 4.0.30319.34280 built by: FX452RTMGDR
    基本代码: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
mscorlib.resources
    程序集版本: 4.0.0.0
    Win32 版本: 4.0.30319.17929 built by: FX45RTMREL
    基本代码: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
System.Windows.Forms.resources
    程序集版本: 4.0.0.0
    Win32 版本: 4.0.30319.17929 built by: FX45RTMREL
    基本代码: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

************** JIT 调试 **************
要启用实时(JIT)调试，
该应用程序或计算机的 .config 文件(machine.config)的 system.windows.forms 节中必须设置
jitDebugging 值。
编译应用程序时还必须启用
调试。

例如: 

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

启用 JIT 调试后，任何未经处理的异常
都将被发送到在此计算机上注册的 JIT 调试器，
而不是由此对话框处理。

**Comment by vmvz** [comment]
谢谢

**Comment by Mrs4s** [comment]
你试着以管理员身份运行试试 应该是没权限

**Comment by vmvz** [comment]
下载速度给力，基本能达到 3-5M/s  （迅雷离线最快16M/s的带宽）

相对于原来客户端 1M的速度，很好了。

是不是都需要把文件放到 对应文件夹？

**Comment by Mrs4s** [comment]
你调下设置的下载带宽 还能更快
