### ISSUE TITLE
提交"更新容量信息时出现错误"bug时请看这里

### ISSUE THREAD

**Issue by Mrs4s** [Mrs4s/BaiduPanDownload#88]
这是百度吧API Key和谐了导致的
将尽快修复这个"BUG"

**Comment by Mrs4s** [comment]
另外目前还能直接从分享链接下载,网盘内下载将尽快恢复

**Comment by now163** [comment]
强烈资词~~

**Comment by linfeng139** [comment]
下了一半就停了QAQ

**Comment by wyy8087** [comment]
百度这和谐速度。。。┭┮﹏┭┮

**Comment by wj36000** [comment]
等你的好消息。。。。。。

**Comment by a67266592** [comment]
分享链接下载,的浏览器插件是什么意思，不知道怎么用

**Comment by ppdan** [comment]
干吧得

**Comment by a67266592** [comment]
最好弄个手动版，我宁可手动辛苦点，只要支持文件夹解析就好，关键是永久性最重要

**Comment by ddggh5566** [comment]
开发者加油( • ̀ω•́ )✧

**Comment by fatelight1997** [comment]
加油！

**Comment by bubbleb** [comment]
浏览器插件只能用aria2下载呀，不会啊  ：（

**Comment by uruz7z** [comment]
别家的直连还正常，不清楚发生了什么

**Comment by shineme** [comment]
人一多 百度就封杀严重了

**Comment by Clancyli** [comment]
大神什么叫“直接从分享链接下载”啊？不会。。

**Comment by dbskccc** [comment]
@Mrs4s 出个教程让各人使用自己的api key才是正道,就像大家用gae一样

**Comment by zpaqws135** [comment]
加油罗~~

**Comment by richermen** [comment]
“直接从分享链接下载”是神马意思

**Comment by shineme** [comment]
让各人使用自己的api key才是正道,就像大家用gae一样

**Comment by soulomoon** [comment]
求分享连接

**Comment by 4nolove** [comment]
好的 不懂编程 但是必须支持一下，这个目前用过的最好用的加速工具了！

**Comment by 690055855** [comment]
支持

**Comment by donly** [comment]
加油！

**Comment by caihuach** [comment]
奸爸爹

**Comment by TIL-MICE** [comment]
加油加油

**Comment by notuglyboy** [comment]
博主碉堡了

**Comment by hynum** [comment]
修复了么

**Comment by HououinKiyouma** [comment]
有人把这个拿去卖，估计就传播开来，引起百度方面重视了，，，真是不作就不会死

**Comment by luanzhuang** [comment]
还有人卖的 这可是坑老人了

**Comment by wyy8087** [comment]
博主停更了吧，我们在那“捐款”，有些人拿出去卖，帮别人赚钱没意思

**Comment by linfeng139** [comment]
加油！百度云会员太贵了，这个价不如买115⊙﹏⊙∥

**Comment by 690055855** [comment]
不要停更啊，我觉得这个很好的

**Comment by haotan007** [comment]
还打推新版本吗，博主

**Comment by okcy1016** [comment]
Be careful coz that there are always people who wanna make money....
if they sold your project for money,I thought it's awful for you and us,before whatever you do,
would you mind adding some identification which is essential,just like this website says.
[https://simplenetkeeper.com/forum/t/381](url)
That guy is also a individual programmer and he coded a software for the limit broadband in colleges.
Hope it will be helpful to your situation now,anyway,thanks for you hardwork~
And by the way,I'm a Chinese,A-Huh-huh-哈-哈-哈哈！ ＞▂＜

**Comment by wyy8087** [comment]
再发一次，哈哈哈哈，还是不建议博主继续更新，如果意已决的话，就像上面那位老兄说的那样，加一些必要的标志，越多越好，一定不能让那些人赚昧良心的钱

**Comment by Mrs4s** [comment]
最新进度: 成功恢复浏览文件和下载功能,下载速度为20M左右 正在修复周边功能

**Comment by notuglyboy** [comment]
博主太他妈帅了

**Comment by Kannnnng** [comment]
非常支持博主，就算是不能坚持多久，但是本科期间就能够做一些这样的作品，对博主你的能力是很好的证明

**Comment by bulibulibulibuli** [comment]
能下载了吗0.0居然有人拿去卖。。。。一开始就猜到了会这样，第一次打开都有提示低调使用。。。

**Comment by Nrsmc** [comment]
现在有什么方法能下载云盘内的东西吗 有点急

**Comment by Mrs4s** [comment]
@Kannnnng 其实这个程序用没有用什么牛逼的技术 基本会基础的都能写

**Comment by luanzhuang** [comment]
这个是要编程吧 小白能学会么

**Comment by befreeeeee** [comment]
现在有什么方法能下载云盘内的东西吗 有点急     非常着急！！！

**Comment by wengjincheng** [comment]
虽然不会c# 但是支持楼主啊。

**Comment by wangbin110** [comment]
有开发讨论群吗？

**Comment by Andrew-Jiang** [comment]
楼主加油!! 不能爱你更多

**Comment by beunsp** [comment]
When can I restore it?

**Comment by notuglyboy** [comment]
@Mrs4s 博主请问这个原理是什么？能简单说一下吗？

**Comment by dsaasds** [comment]
@Mrs4s 博主分享链接也挂了。

**Comment by cman08** [comment]
继续等待博主的好消息。

**Comment by cman08** [comment]
博主会把更新放在这儿吗？

**Comment by Cologler** [comment]
如果 github 提供一个选项给项目像「去年没有 500 次贡献不能看」之类的功能就好了。

**Comment by ljh1297599698** [comment]
支持博主，加油0.0

**Comment by orekikoush** [comment]
坐等新版本发布

**Comment by 4nolove** [comment]
这么好的坐骑不能骑了，我的内心是崩溃的。

**Comment by nsktpi** [comment]
骑呀

**Comment by yuanyaozi** [comment]
居然还有人拿去卖，私下交流用还不够么

**Comment by yuanyaozi** [comment]
居然还有人拿去卖，私下交流用还不够么

**Comment by meteoryxx** [comment]
被百度发现了啊，不然怎么会动apikey

**Comment by nsktpi** [comment]
当然发现了呀
要不然他怎么叫百度云？

**Comment by GOLDROBERT** [comment]
好像又 更新信息 错误了...

**Comment by Dearmw** [comment]
加油!!

**Comment by bulibulibulibuli** [comment]
其实Aria2一样下载，暂时先用着还是不错的。。。虽然比坐骑麻烦点。

**Comment by yizhiren203** [comment]
何时能修复好啊！！！

**Comment by bulibulibulibuli** [comment]
先用分享页下载先吧。。等博主好消息

**Comment by wyy8087** [comment]
安装了插件怎么还是监听失败

**Comment by Nrsmc** [comment]
给个方法下载啊 简单点的

**Comment by Mrs4s** [comment]
进度可以加群 237331031 讨论

**Comment by Cologler** [comment]
这是开源项目，全靠作者兴趣写的，伸手党也就算了，怎么还有人催更？

**Comment by nsktpi** [comment]
不要催更
只要在写一个新的出来就好

**Comment by cman08** [comment]
已申请加群，理由“百度网盘不限速下载工具——支持收费筛选用户”。
希望入选。

**Comment by Mrtahiti** [comment]
支持，所以下载新版需要进群吗？

**Comment by Kannnnng** [comment]
@Cologler 想必上面的好多同学在此之前根本就不知道Git是什么，更别提开源项目，只是单纯注册一个账号做伸手党罢了

**Comment by a67266592** [comment]
如果发现开源，收费等现象，我们会立刻通知国际律师起诉相关人，按导致百度公司亏损额度赔偿，同时刑事责任一并承担，举报电话：010-59922822，优先举报者，可以获得2000元奖励

**Comment by a67266592** [comment]
如果发现开源，收费等现象，我们会立刻通知国际律师起诉相关人，按导致百度公司亏损额度赔偿，同时刑事责任一并承担，举报电话：010-59922822，优先举报者，可以获得2000元奖励

**Comment by bulibulibulibuli** [comment]
不允许任何人进群0.0

**Comment by befreeeeee** [comment]
不允许任何人进群

**Comment by huhugood** [comment]
m,,

**Comment by lzclzclzchhh** [comment]
群加不进去...

**Comment by syguorong** [comment]
加群没反应，哎。。。。。

**Comment by lzclzclzchhh** [comment]
@Mrs4s 申请加群

**Comment by huhugood** [comment]
I want to add a group！！！！！！！！！！

**Comment by MisakaMiko** [comment]
Q群满人了，进不去了

**Comment by HongZai21** [comment]
想问下修好了吗？好多东西想下载，百度云管家都5-10 kb 下载 T^T

**Comment by kang0024** [comment]
已发出申请，求进群。

**Comment by wrylx1989** [comment]
@Mrs4s 楼主，加不进去群啊，如何进群啊，跪求

**Comment by GrandJIE** [comment]
为什么我用aria2速度也不超过100KB，真是好慢

**Comment by syguorong** [comment]
楼主有新的更新了吗？？

**Comment by lihua678** [comment]
好好的，为什么加群？

**Comment by LeslieSong** [comment]
两个群都加不进去

**Comment by wangling01shi** [comment]
@Mrs4s  求进群 !

**Comment by roseashe** [comment]
求问进群的答案的是什么

**Comment by qwas982** [comment]
# **希望增加内存缓存的功能.可以自由设置大小,1GB-4GB的容量**

**Comment by syguorong** [comment]
楼主有新的更新了 吗？

**Comment by Mrs4s** [comment]
已修复

**Comment by xxppff** [comment]
作者你好，老司机工具，我点登陆没反应，弹出的页面打开不了百度账号登陆界面，这是为啥啊

**Comment by HongZai21** [comment]
无法登陆@@
