### ISSUE TITLE
博主，现在进程到哪里了呀，等得好着急啊~加油

### ISSUE THREAD

**Issue by 690055855** [Mrs4s/BaiduPanDownload#91]

**Comment by nsktpi** [comment]
假的，哎呀我的眼睛业障重啊！

**Comment by yep96** [comment]
+1还有一个问题，就是打开坐骑下载后，无论机械还是固盘，直接用到100%，暂停或者断网都没有用，要占用很久，任务管理器也关不了。。

**Comment by Mrs4s** [comment]
进度可以加群237331031

**Comment by wxwssg** [comment]
@Mrs4s 
博主的软件挂了后，又搜到了一个同类型的软件，这个还能用。博主也参考下吧。
[地址戳这](https://github.com/gy12346123/BaiduCloudSupport)

**Comment by Mrs4s** [comment]
@wxwssg 这个已经被限速了
我目前有逻辑实现不限速
