### ISSUE TITLE
项目导入vs中报错，是缺少什么库文件么？求帮忙看一下

### ISSUE THREAD

**Issue by Chenyyq** [Mrs4s/BaiduPanDownload#95]
1. 

public int NetSpeed { get; set; } _=_ 30;
报错：错误	31	类、结构或接口成员声明中的标记“=”无效	C:\Users\chenyq\Desktop\BaiduPanDownload-master\BaiduPanDownload-master\BaiduPanDownload\Util\FileTool\Config.cs	19	41	BaiduPanDownload

2. 

public ArrayList DownloadList { get; set; } = _new ArrayList()_;
错误	36	方法必须具有返回类型	C:\Users\chenyq\Desktop\BaiduPanDownload-master\BaiduPanDownload-master\BaiduPanDownload\Util\FileTool\Config.cs	22	59	BaiduPanDownload

3. 

textBox1.Text += _$"https://pcs.baidu.com/rest/2.0/pcs/file?method=download&access_token={Program.config.Access_Token}&path=" + Uri.EscapeDataString(SubFile.path)+"\r\n"_;
错误	93	只有 assignment、call、increment、decrement、await 和 new 对象表达式可用作语句	C:\Users\chenyq\Desktop\BaiduPanDownload-master\BaiduPanDownload-master\BaiduPanDownload\Forms\Download.cs	64	39	BaiduPanDownload

# 好像是形如 public class name{get;set;} = new name();形式都会报错。

**已经使用了net farmework 4.5.2框架；相关的NuGet包也导入了，有foby，json.NET，log4net。**

==============================================================
### **目前使用的vs的信息**
Microsoft Visual Studio Ultimate 2013
版本 12.0.31101.00 Update 4
Microsoft .NET Framework
版本 4.6.01586

已安装的版本: Ultimate

LightSwitch for Visual Studio 2013   06181-004-0451047-02329
Microsoft LightSwitch for Visual Studio 2013

Visual Basic 2013   06181-004-0451047-02329
Microsoft Visual Basic 2013

Visual C# 2013   06181-004-0451047-02329
Microsoft Visual C# 2013

Visual C++ 2013   06181-004-0451047-02329
Microsoft Visual C++ 2013

Visual F# 2013   06181-004-0451047-02329
Microsoft Visual F# 2013

Visual Studio 2013 代码分析拼写检查器   06181-004-0451047-02329
Microsoft® Visual Studio® 2013 代码分析拼写检查器

International CorrectSpell™ spelling correction system © 1993 部分版权归 Lernout & Hauspie Speech Products N.V. 所有。保留所有权利。

The American Heritage® Dictionary of the English Language 第三版，版权所有© 1992 Houghton Mifflin Company。获得 Lernout & Hauspie Speech Products N.V. 的电子版许可。保留所有权利。

Visual Studio 2013 的团队资源管理器   06181-004-0451047-02329
Microsoft Visual Studio 2013 的团队资源管理器

体系结构和建模工具   06181-004-0451047-02329
Microsoft 体系结构和建模工具
    
UML(R) 和 Unified Modeling Language(TM) 是 Object Management Group, Inc. 在美国和其他国家/地区的商标或注册商标。

ASP.NET Web Frameworks and Tools 2012.2   4.1.21001.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.21010.0
For additional information, visit http://www.asp.net/

ASP.NET 和 Web 工具   12.4.51016.0
Microsoft Web Developer Tools 包含以下组件:
支持创建和打开 ASP.NET Web 项目
Browser Link: Visual Studio 和浏览器之间的通信通道
用于 HTML、CSS 和 JavaScript 的编辑器扩展
Page Inspector: 用于 ASP.NET Web 项目的检查工具
基架: 用于构建和运行代码生成器的框架
用于 Microsoft Azure 网站的服务器资源管理器扩展
Web 发布: 用于将 ASP.NET Web 项目发布到宿主提供程序、本地服务器或 Microsoft Azure 的扩展

Microsoft Azure 移动服务工具   1.3
Microsoft Azure 移动服务工具

NuGet 程序包管理器   2.8.50926.663
Visual Studio 中的 NuGet 程序包管理器。有关 NuGet 的详细信息，请访问 http://docs.nuget.org/。

PowerShell 工具   1.3
提供使用 PowerShell 的文件分类服务

PreEmptive Analytics 可视化工具   1.2
Microsoft Visual Studio 扩展可以可视化 PreEmptive Analytics 产品的聚合摘要。

Release Management for Visual Studio Package   1.0
Release Management for Visual Studio

SQL Server Data Tools   12.0.41012.0
Microsoft SQL Server Data Tools

Visual Studio 2013 的 Office 开发工具(简体中文)   12.0.30626
Microsoft Visual Studio 2013 的 Office 开发工具(简体中文)

Visual Studio Tools for Unity   2.0.0.0
Visual Studio Tools for Unity

Windows Phone 8.1 SDK 集成   1.0
此程序包将 Windows Phone 8.1 SDK 的工具集成到 Visual Studio 菜单和控件中。

Workflow Manager Tools 1.0   1.0
此程序包包含 Workflow Manager 的必要 Visual Studio 集成组件。

通用 Azure 工具   1.3
通过 Azure 移动服务和 Microsoft Azure 工具提供通用服务。
---------------------------------------------------------------------

**Comment by Mrs4s** [comment]
vs版本太低了

**Comment by wingsziye** [comment]
使用VS 2015吧。。
