### ISSUE TITLE
1.8.0 百度登陆界面打不开

### ISSUE THREAD

**Issue by kang0024** [Mrs4s/BaiduPanDownload#99]

**Comment by jackyjjp** [comment]
:(
缓存文件写入失败！:./Applications/Runtime/Cache/Index/b5a92b6ad8deb3167241e2b1fdf64f7b.php
错误位置
/www/web/139/public_html/Appwork/Lib/Template/ThinkTemplate.class.php 　LINE: 123

111                 $layoutFile  =  THEME_PATH.C('LAYOUT_NAME').$this->config['template_suffix'];
112                 $tmplContent = str_replace($this->config['layout_item'],$tmplContent,file_get_contents($layoutFile));
113             }
114         }
115         // 编译模板内容
116         $tmplContent =  $this->compiler($tmplContent);
117         // 检测模板目录
118         $dir         =  dirname($tmplCacheFile);
119         if(!is_dir($dir))
120             mkdir($dir,0755,true);
121         //重写Cache文件
122         if( false === file_put_contents($tmplCacheFile,trim($tmplContent)))
123             throw_exception(L('_CACHE_WRITE_ERROR_').':'.$tmplCacheFile);
124         return $tmplCacheFile;
125     }
126 
127     /**
128      * 编译模板文件内容
129      * @access protected
130      * @param mixed $tmplContent 模板内容
131      * @return string
132      */
133     protected function compiler($tmplContent) {
134         //模板解析
135         $tmplContent =  $this->parse($tmplContent);

**Comment by nailongzhenren** [comment]
我也是这样
